// Vaporly appearance, one shared helper used by both webview windows (main and
// overlay). v2 ships SIX curated accent presets, each a pair of verified
// light/dark stop sets derived from the sakura anatomy at matched OKLCH
// lightness/chroma with the deep stops darkened per hue until the contrast
// gates pass (white-on-solid >= 4.5, accent ink >= 4.5 on the light surfaces,
// focus ring >= 3). Painting the stops inline on :root guarantees a flash-free
// first paint; the compat aliases in theme.css carry --color-accent to the
// legacy --color-logo-primary / --color-background-ui names the overlay still
// reads. The theme MODE (system/light/dark) rides the same helper: it stamps
// data-theme on the root element, which the theme.css selectors key off.

export type ThemeMode = "system" | "light" | "dark";

export type AccentPreset =
  "sakura" | "rose" | "amber" | "green" | "blue" | "violet";

type AccentStops = {
  accent: string;
  accentInk: string;
  tint: string;
  solid: string;
  solidHover: string;
  solidActive: string;
  stroke: string;
  focusRing: string;
  surfaceSelected: string;
};

// Generated by scratchpad gen_accent_presets.py (OKLCH hue rotation from the
// sakura stops + per-hue deep-trio darkening); every preset passes the same
// contrast gates the sakura palette shipped with.
export const PRESETS: Record<
  AccentPreset,
  { light: AccentStops; dark: AccentStops }
> = {
  sakura: {
    light: {
      accent: "#f8b0d3",
      accentInk: "#b44261",
      tint: "#fde5f0",
      solid: "#c44c6c",
      solidHover: "#b44261",
      solidActive: "#a53856",
      stroke: "#b34a6a",
      focusRing: "#b44261",
      surfaceSelected: "#f9bfda",
    },
    dark: {
      accent: "#f9bfda",
      accentInk: "#f9bfda",
      tint: "#4f3341",
      solid: "#c44c6c",
      solidHover: "#b44261",
      solidActive: "#a53856",
      stroke: "#ffd6e2",
      focusRing: "#f9bfda",
      surfaceSelected: "#6f3852",
    },
  },
  rose: {
    light: {
      accent: "#ffb2ab",
      accentInk: "#b74441",
      tint: "#ffe6e3",
      solid: "#c64d49",
      solidHover: "#b74441",
      solidActive: "#a83a38",
      stroke: "#b74441",
      focusRing: "#b74441",
      surfaceSelected: "#ffc1bb",
    },
    dark: {
      accent: "#ffc1bb",
      accentInk: "#ffc1bb",
      tint: "#523331",
      solid: "#c64d49",
      solidHover: "#b74441",
      solidActive: "#a83a38",
      stroke: "#ffd8d4",
      focusRing: "#ffc1bb",
      surfaceSelected: "#743935",
    },
  },
  amber: {
    light: {
      accent: "#edc082",
      accentInk: "#936302",
      tint: "#f9ead7",
      solid: "#9f6b03",
      solidHover: "#936302",
      solidActive: "#875a02",
      stroke: "#936302",
      focusRing: "#936302",
      surfaceSelected: "#f0cc9c",
    },
    dark: {
      accent: "#f0cc9c",
      accentInk: "#f0cc9c",
      tint: "#4b3921",
      solid: "#9f6b03",
      solidHover: "#936302",
      solidActive: "#875a02",
      stroke: "#f6dfc0",
      focusRing: "#f0cc9c",
      surfaceSelected: "#674508",
    },
  },
  green: {
    light: {
      accent: "#9cdba9",
      accentInk: "#007e37",
      tint: "#dff3e2",
      solid: "#01883d",
      solidHover: "#007e37",
      solidActive: "#007936",
      stroke: "#007e37",
      focusRing: "#007e37",
      surfaceSelected: "#b0e1b9",
    },
    dark: {
      accent: "#b0e1b9",
      accentInk: "#b0e1b9",
      tint: "#2b4430",
      solid: "#01883d",
      solidHover: "#007e37",
      solidActive: "#007936",
      stroke: "#cdecd2",
      focusRing: "#b0e1b9",
      surfaceSelected: "#265a33",
    },
  },
  blue: {
    light: {
      accent: "#a5ccff",
      accentInk: "#246ec1",
      tint: "#e1eeff",
      solid: "#2a76ce",
      solidHover: "#246ec1",
      solidActive: "#1e64b5",
      stroke: "#246ec1",
      focusRing: "#246ec1",
      surfaceSelected: "#b5d5ff",
    },
    dark: {
      accent: "#b5d5ff",
      accentInk: "#b5d5ff",
      tint: "#2c3e55",
      solid: "#2a76ce",
      solidHover: "#246ec1",
      solidActive: "#1e64b5",
      stroke: "#d0e5ff",
      focusRing: "#b5d5ff",
      surfaceSelected: "#2b4e7a",
    },
  },
  violet: {
    light: {
      accent: "#d7bafb",
      accentInk: "#8555b5",
      tint: "#f1e8fd",
      solid: "#905ec3",
      solidHover: "#8555b5",
      solidActive: "#784aa6",
      stroke: "#8555b5",
      focusRing: "#8555b5",
      surfaceSelected: "#dec7fa",
    },
    dark: {
      accent: "#dec7fa",
      accentInk: "#dec7fa",
      tint: "#423750",
      solid: "#905ec3",
      solidHover: "#8555b5",
      solidActive: "#784aa6",
      stroke: "#eadbfd",
      focusRing: "#dec7fa",
      surfaceSelected: "#584072",
    },
  },
};

/** The default (light sakura) accent, kept as a stable export. */
export const DEFAULT_ACCENT = PRESETS.sakura.light.accent;

// The applied appearance. Defaults match a fresh install (system + sakura) so
// the pre-settings first paint is correct without a store read.
let currentPreset: AccentPreset = "sakura";

/**
 * True when the effective theme is dark: OS dark unless data-theme forces light,
 * or data-theme explicitly forces dark. Mirrors the CSS selector logic in
 * theme.css so JS and CSS never disagree.
 */
function isDark(): boolean {
  const forced = document.documentElement.dataset.theme;
  const osDark = window.matchMedia("(prefers-color-scheme: dark)").matches;
  return (osDark && forced !== "light") || forced === "dark";
}

/** Paint the current preset's stops for the current theme onto :root. */
function paint(): void {
  const pair = PRESETS[currentPreset] ?? PRESETS.sakura;
  const s = isDark() ? pair.dark : pair.light;
  const root = document.documentElement.style;
  root.setProperty("--color-accent", s.accent);
  root.setProperty("--color-accent-ink", s.accentInk);
  root.setProperty("--color-accent-tint", s.tint);
  root.setProperty("--color-accent-solid", s.solid);
  root.setProperty("--color-accent-solid-hover", s.solidHover);
  root.setProperty("--color-accent-solid-active", s.solidActive);
  root.setProperty("--color-logo-stroke", s.stroke);
  root.setProperty("--color-focus-ring", s.focusRing);
  root.setProperty("--color-surface-selected", s.surfaceSelected);
}

/**
 * Apply a stored appearance: stamp (or clear) data-theme for the mode, adopt
 * the accent preset, and repaint. Call whenever the settings load or change.
 */
export function applyAppearance(mode: ThemeMode, preset: AccentPreset): void {
  const root = document.documentElement;
  if (mode === "system") {
    delete root.dataset.theme;
  } else {
    root.dataset.theme = mode;
  }
  currentPreset = PRESETS[preset] ? preset : "sakura";
  paint();
}

/** Re-apply the accent for the current theme. Call after flipping data-theme. */
export function repaintAccent(): void {
  paint();
}

/**
 * Bootstrap for a window entry: paint the default appearance synchronously
 * (no flash) and re-paint when the OS light/dark mode flips. Safe to call in
 * any window; the stored appearance is applied on top once settings load.
 */
export function bootstrapAccent(): void {
  paint();
  window
    .matchMedia("(prefers-color-scheme: dark)")
    .addEventListener("change", () => paint());
}
