
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async changeBinding(id: string, binding: string) : Promise<Result<BindingResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_binding", { id, binding }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetBinding(id: string) : Promise<Result<BindingResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_binding", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Temporarily unregister a binding while the user is editing it in the UI.
 * This avoids firing the action while keys are being recorded.
 */
async suspendBinding(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("suspend_binding", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-register the binding after the user has finished editing.
 */
async resumeBinding(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_binding", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeGlobeKeyNoticeDismissedSetting(dismissed: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_globe_key_notice_dismissed_setting", { dismissed }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAudioFeedbackSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_audio_feedback_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAudioFeedbackVolumeSetting(volume: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_audio_feedback_volume_setting", { volume }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeSoundThemeSetting(theme: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_sound_theme_setting", { theme }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAutostartSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_autostart_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeUpdateChecksSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_update_checks_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeOverlayPositionSetting(position: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_overlay_position_setting", { position }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeOverlayStyleSetting(style: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_overlay_style_setting", { style }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAppendTrailingSpaceSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_append_trailing_space_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeKeepResultOnClipboardSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_keep_result_on_clipboard_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeOnboardingCompletedSetting(completed: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_onboarding_completed_setting", { completed }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeCustomWordsLevelSetting(level: FeatureLevel) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_custom_words_level_setting", { level }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeCustomPhrasesLevelSetting(level: FeatureLevel) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_custom_phrases_level_setting", { level }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeWhisperModeSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_whisper_mode_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeWhisperStrengthSetting(strength: WhisperStrength) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_whisper_strength_setting", { strength }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeThemeModeSetting(mode: ThemeMode) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_theme_mode_setting", { mode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAccentPresetSetting(preset: AccentPreset) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_accent_preset_setting", { preset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeFillerLevelSetting(level: FeatureLevel) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_filler_level_setting", { level }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeFillerEngineSetting(engine: StageEngine) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_filler_engine_setting", { engine }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeMindChangeLevelSetting(level: FeatureLevel) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_mind_change_level_setting", { level }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeMindChangeEngineSetting(engine: StageEngine) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_mind_change_engine_setting", { engine }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeContextAwarenessSetting(value: ContextAwarenessSettings) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_context_awareness_setting", { value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAutoLearnModeSetting(mode: AutoLearnMode) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_auto_learn_mode_setting", { mode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateCustomWords(words: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_custom_words", { words }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateCustomPhrases(phrases: CustomPhrase[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_custom_phrases", { phrases }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Change the keyboard implementation with runtime switching.
 * This will unregister all shortcuts from the old implementation,
 * validate shortcuts for the new implementation (resetting invalid ones to defaults),
 * and register them with the new implementation.
 */
async changeKeyboardImplementationSetting(implementation: string) : Promise<Result<ImplementationChangeResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_keyboard_implementation_setting", { implementation }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the current keyboard implementation
 */
async getKeyboardImplementation() : Promise<string> {
    return await TAURI_INVOKE("get_keyboard_implementation");
},
/**
 * Start key recording mode
 */
async startNativeKeysRecording(bindingId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_native_keys_recording", { bindingId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop key recording mode
 */
async stopNativeKeysRecording() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_native_keys_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async triggerUpdateCheck() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("trigger_update_check") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showMainWindowCommand() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_main_window_command") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelOperation() : Promise<void> {
    await TAURI_INVOKE("cancel_operation");
},
async isPortable() : Promise<boolean> {
    return await TAURI_INVOKE("is_portable");
},
async getAppDirPath() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_dir_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAppSettings() : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDefaultSettings() : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_default_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLogDirPath() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_log_dir_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openRecordingsFolder() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_recordings_folder") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openLogDir() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_log_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openAppDataDir() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_app_data_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Try to initialize Enigo (keyboard/mouse simulation).
 * On macOS, this will return an error if accessibility permissions are not granted.
 */
async initializeEnigo() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("initialize_enigo") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Initialize keyboard shortcuts.
 * On macOS, this should be called after accessibility permissions are granted.
 * This is idempotent - calling it multiple times is safe.
 */
async initializeShortcuts() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("initialize_shortcuts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reset every setting to its shipped default. History, recordings, and
 * downloaded models are untouched. The onboarding marker is kept so the user
 * is not re-onboarded.
 */
async resetAllSettings() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_all_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-run first-run onboarding on the next launch.
 */
async resetOnboarding() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_onboarding") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableModels() : Promise<Result<ModelInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getModelInfo(modelId: string) : Promise<Result<ModelInfo | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_model_info", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelDownload(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_download", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTranscriptionModelStatus() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_transcription_model_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isModelLoading() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_model_loading") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLlmEngineStatus() : Promise<EngineStatus> {
    return await TAURI_INVOKE("get_llm_engine_status");
},
async restartLlmEngine() : Promise<void> {
    await TAURI_INVOKE("restart_llm_engine");
},
async getHardwareProfile() : Promise<HardwareProfile> {
    return await TAURI_INVOKE("get_hardware_profile");
},
async getLlmModels() : Promise<LlmModelStatus[]> {
    return await TAURI_INVOKE("get_llm_models");
},
async downloadLlmModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_llm_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelLlmModelDownload(modelId: string) : Promise<void> {
    await TAURI_INVOKE("cancel_llm_model_download", { modelId });
},
async deleteLlmModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_llm_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setLlmModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_llm_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * One tiny completion through the live engine, the settings "Test" button
 * and the onboarding finish check.
 */
async llmEngineSelftest() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("llm_engine_selftest") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWindowsMicrophonePermissionStatus() : Promise<WindowsMicrophonePermissionStatus> {
    return await TAURI_INVOKE("get_windows_microphone_permission_status");
},
async openMicrophonePrivacySettings() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_microphone_privacy_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableMicrophones() : Promise<Result<AudioDevice[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_microphones") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSelectedMicrophone(deviceName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_selected_microphone", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSelectedMicrophone() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_selected_microphone") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableOutputDevices() : Promise<Result<AudioDevice[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_output_devices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSelectedOutputDevice(deviceName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_selected_output_device", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSelectedOutputDevice() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_selected_output_device") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async playTestSound(soundType: string) : Promise<void> {
    await TAURI_INVOKE("play_test_sound", { soundType });
},
async checkCustomSounds() : Promise<CustomSounds> {
    return await TAURI_INVOKE("check_custom_sounds");
},
/**
 * Begin one RAW capture phase for the whisper calibration wizard (wizard
 * v2): the mic opens with the gate, booster, and VAD all bypassed and
 * records until `whisper_calibration_phase_stop`. The wizard runs three
 * phases (ambient, normal voice, whisper), each ended by the user pressing
 * Continue after its 5 second unlock. Momentary by design: nothing keeps
 * running outside an active phase.
 */
async whisperCalibrationPhaseStart() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("whisper_calibration_phase_start") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * End the current wizard phase and return its level stats. Doubles as the
 * cancel path: the wizard calls this and discards the result.
 */
async whisperCalibrationPhaseStop() : Promise<Result<CalibrationPhaseStats, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("whisper_calibration_phase_stop") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Turn the three measured wizard levels into a stored per-mic calibration
 * and return it for display. Overwrites any previous calibration.
 */
async whisperCalibrationFinish(ambient: number, normal: number, whisper: number) : Promise<Result<WhisperCalibration, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("whisper_calibration_finish", { ambient, normal, whisper }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove the stored calibration: the gate returns to the strength defaults.
 */
async whisperCalibrationClear() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("whisper_calibration_clear") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isRecording() : Promise<boolean> {
    return await TAURI_INVOKE("is_recording");
},
async getModelLoadStatus() : Promise<Result<ModelLoadStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_model_load_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unloadModelManually() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unload_model_manually") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHistoryEntries(cursor: number | null, limit: number | null) : Promise<Result<PaginatedHistory, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_history_entries", { cursor, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchHistoryEntries(query: string, limit: number | null) : Promise<Result<HistoryEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_history_entries", { query, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAudioFilePath(fileName: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_audio_file_path", { fileName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteHistoryEntry(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_history_entry", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async retryHistoryEntryTranscription(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("retry_history_entry_transcription", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Edit a history entry's displayed text (the post-processed text when the
 * entry has one, else the raw transcription). Emits the Updated payload so
 * open lists refresh. In the HistoryEdits/Both auto-learn modes the old vs
 * new diff feeds the custom-word learn funnel (F4).
 */
async updateHistoryEntryText(id: number, text: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_history_entry_text", { id, text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateHistoryLimit(limit: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_history_limit", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateRecordingRetentionPeriod(period: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_recording_retention_period", { period }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
historyUpdatePayload: HistoryUpdatePayload,
streamPhaseEvent: StreamPhaseEvent,
streamTextEvent: StreamTextEvent
}>({
historyUpdatePayload: "history-update-payload",
streamPhaseEvent: "stream-phase-event",
streamTextEvent: "stream-text-event"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * Curated accent preset. Each maps to a verified light/dark stop set in the
 * frontend (src/styles/applyAccent.ts); the backend only stores the choice.
 */
export type AccentPreset = "sakura" | "rose" | "amber" | "green" | "blue" | "violet"
/**
 * Vaporly settings, fresh schema (version 1). No serde aliases and no value
 * migrations: v2 starts with its own store. Unreadable stores are quarantined
 * (see below) and replaced with defaults.
 */
export type AppSettings = { 
/**
 * Settings schema marker for future one-time migrations.
 */
settings_schema_version?: number; onboarding_completed?: boolean; bindings: Partial<{ [key in string]: ShortcutBinding }>; keyboard_implementation?: KeyboardImplementation; 
/**
 * One-time dismissal of the macOS globe-key tip shown when a binding
 * uses fn (System Settings, Keyboard, "Press globe key to" = Do Nothing).
 */
globe_key_notice_dismissed?: boolean; selected_microphone?: string | null; audio_feedback?: boolean; audio_feedback_volume?: number; sound_theme?: SoundTheme; selected_output_device?: string | null; 
/**
 * Theme mode: follow the OS or force light/dark (both windows).
 */
theme_mode?: ThemeMode; 
/**
 * Accent color preset (both windows).
 */
accent_preset?: AccentPreset; 
/**
 * Whisper Mode: boost quiet speech (hotter auto-gain + a relaxed VAD
 * gate) so whispering still transcribes. Applies from the next dictation.
 */
whisper_mode?: boolean; 
/**
 * How hard Whisper Mode boosts (gain target/cap + VAD relax).
 */
whisper_strength?: WhisperStrength; 
/**
 * Optional per-mic calibration from the wizard; None = strength defaults.
 */
whisper_calibration?: WhisperCalibration | null; overlay_style?: OverlayStyle; overlay_position?: OverlayPosition; 
/**
 * Custom-word fuzzy correction aggressiveness (Off disables the stage).
 */
custom_words_level?: FeatureLevel; custom_words?: string[]; custom_phrases?: CustomPhrase[]; 
/**
 * Custom-phrase trigger matching aggressiveness (Off disables the stage;
 * single-word triggers stay exact at every level).
 */
custom_phrases_level?: FeatureLevel; 
/**
 * Filler fix up dial (um/uh removal and friends).
 */
filler_level?: FeatureLevel; filler_engine?: StageEngine; 
/**
 * Mind-changing check dial ("at eight, no wait, nine" -> "at nine").
 * Default: High on the MODEL engine (the deterministic Medium pass alone
 * misses too many spoken corrections; High+Model resolves explicit
 * retractions with the LLM while the deterministic stages still do
 * numbers/words/caps first).
 */
mind_change_level?: FeatureLevel; mind_change_engine?: StageEngine; context_awareness?: ContextAwarenessSettings; auto_learn_mode?: AutoLearnMode; 
/**
 * After pasting, keep the final text on the clipboard (true) or restore
 * the previous clipboard contents (false).
 */
keep_result_on_clipboard?: boolean; append_trailing_space?: boolean; autostart_enabled?: boolean; update_checks_enabled?: boolean; history_limit?: number; recording_retention_period?: RecordingRetentionPeriod; 
/**
 * Cleanup model for the bundled engine. Empty = the hardware ladder's
 * recommendation (7B on >=14GB machines, 1.5B on 6-14GB, none below).
 */
llm_model_id?: string }
export type AudioDevice = { index: string; name: string; is_default: boolean }
/**
 * Auto-learning of custom words (F4). WatchPostPaste is the macOS AX
 * observation mode, experimental by contract.
 */
export type AutoLearnMode = "off" | "history_edits" | "repeated_words" | "both" | "watch_post_paste"
export type BindingResponse = { success: boolean; binding: ShortcutBinding | null; error: string | null }
/**
 * Per-frame rms stats returned when a wizard phase ends. The wizard uses
 * `mean_rms` for the ambient phase and `p75_rms` for the voice phases (see
 * `whisper_calibrate::phase_stats` for why the percentile).
 */
export type CalibrationPhaseStats = { mean_rms: number; p75_rms: number }
/**
 * Context awareness: which target-app categories adapt formatting, and via
 * which engine.
 */
export type ContextAwarenessSettings = { email: boolean; chat: boolean; code: boolean; browser: boolean; notes: boolean; general: boolean; mode: ContextMode }
/**
 * How context awareness adapts output to the frontmost app: deterministic
 * per-category rules, a model prompt hint, or both.
 */
export type ContextMode = "deterministic" | "model" | "both"
/**
 * Custom Phrases: spoken trigger -> written replacement ("btw" -> "by the
 * way", "write my email format" -> a saved template). Applied
 * deterministically after STT (audio_toolkit::apply_custom_phrases).
 */
export type CustomPhrase = { say: string; write: string }
export type CustomSounds = { start: boolean; stop: boolean }
export type EngineState = 
/**
 * Bundled provider not selected / post-processing off, intentionally down.
 */
"disabled" | 
/**
 * No payload staged for this platform (dev build without the fetch script).
 */
"not_installed" | 
/**
 * Copying the payload from resources into app-data.
 */
"installing" | 
/**
 * Selected cleanup model's GGUF shards are not all in the HF cache.
 */
"model_missing" | 
/**
 * Process launched; /health not answering yet.
 */
"spawning" | 
/**
 * /health says the model is still loading (HTTP 503).
 */
"loading_model" | 
/**
 * /health 200, ENGINE_PORT is live.
 */
"ready" | 
/**
 * Crashed; backoff timer running before the next respawn attempt.
 */
"restarting" | 
/**
 * Gave up after repeated crashes, Repair button resets.
 */
"crashed" | 
/**
 * Deliberately stopped (app exit, model swap, provider switch).
 */
"stopped"
export type EngineStatus = { state: EngineState; port: number; model_id: string; engine_version: string; 
/**
 * Human-oriented detail (last error, crash count, ...). Not localized, /// diagnostic text only.
 */
detail: string }
export type EngineType = 
/**
 * Any GGML/GGUF model loaded through transcribe-cpp (the only engine).
 * The architecture is auto-detected from the file, so this one variant
 * covers the whole transcribe-cpp family.
 */
"TranscribeCpp"
/**
 * Aggressiveness dial shared by the cleanup stages (custom words, filler
 * fix up, mind-changing check).
 */
export type FeatureLevel = "off" | "light" | "medium" | "high"
export type HardwareProfile = { total_ram_gb: number; is_vm: boolean; is_apple_silicon: boolean; tier: Tier; 
/**
 * Catalog id of the ladder's pick (empty for `Raw`, nothing auto-selected).
 */
recommended_model_id: string }
export type HistoryEntry = { id: number; file_name: string; timestamp: number; saved: boolean; title: string; transcription_text: string; post_processed_text: string | null; post_process_prompt: string | null; post_process_requested: boolean; 
/**
 * Vaporly: the app the dictation targeted (frontmost at transcription time).
 */
app_name: string | null }
export type HistoryUpdatePayload = { action: "added"; entry: HistoryEntry } | { action: "updated"; entry: HistoryEntry } | { action: "deleted"; id: number }
/**
 * Result of changing keyboard implementation
 */
export type ImplementationChangeResult = { success: boolean; 
/**
 * List of binding IDs that were reset to defaults due to incompatibility
 */
reset_bindings: string[] }
export type KeyboardImplementation = "tauri" | "vaporly_native"
export type LlmModelInfo = { 
/**
 * Catalog id, e.g. "qwen2.5-7b-instruct-q4_k_m" (also the ladder's key).
 */
id: string; display_name: string; 
/**
 * Hugging Face repo the shards live in.
 */
repo: string; 
/**
 * GGUF shard filenames in order; shard 0 is what `-m` points at.
 */
files: string[]; params_b: number; quant: string; total_bytes: number; 
/**
 * Total machine RAM (GB) where this model runs comfortably.
 */
ram_needed_gb: number; license: string }
export type LlmModelStatus = { info: LlmModelInfo; is_downloaded: boolean; is_downloading: boolean; is_selected: boolean }
export type ModelInfo = { id: string; name: string; description: string; filename: string; source: ModelSource; size_mb: number; is_downloaded: boolean; is_downloading: boolean; partial_size: number; is_directory: boolean; engine_type: EngineType; accuracy_score: number; speed_score: number; supports_translation: boolean; is_recommended: boolean; supported_languages: string[]; supports_language_selection: boolean; is_custom: boolean; supports_streaming: boolean; supports_language_detection: boolean }
export type ModelLoadStatus = { is_loaded: boolean; current_model: string | null }
/**
 * Where a model comes from and how Vaporly obtains it, the routing discriminant
 * for downloading and on-disk resolution.
 */
export type ModelSource = 
/**
 * A file inside a Hugging Face Hub repo, fetched via hf-hub into the shared
 * HF cache (so other tools reuse it). The file within the repo is
 * [`ModelInfo::filename`].
 */
{ HuggingFace: { repo_id: string; revision: string } } | 
/**
 * Already present on disk. Nothing to download.
 */
"Local"
export type OverlayPosition = "top" | "bottom"
/**
 * Which recording overlay to display.
 * - `None`: no overlay at all.
 * - `Bar`: compact status pill (waveform, spinner, result flash).
 * - `BarLive`: the pill grows into a panel showing live transcription text.
 * - `TextboxRaw`: stream committed words straight into the target app, then
 * repair them to the cleaned final text at finish (stream_inject.rs). The
 * overlay stays a compact status pill.
 * - `TextboxClean`: stream cleaned sentences into the target app as each
 * completes (deterministic sentences, or LiveCleaner chunks when a model
 * plan is active). Status pill only.
 * - `Inline`: stream the deterministically filtered live text into the
 * target app UNDERLINED (combining low line per grapheme), polishing each
 * completed sentence in place while the user still speaks; on release the
 * underline goes away and the clean final text stands. Status pill only.
 * All on-textbox styles degrade to Bar behavior for a dictation whose
 * injection preflight fails.
 */
export type OverlayStyle = "none" | "bar" | "bar_live" | "textbox_raw" | "textbox_clean" | 
/**
 * Alias `wispr` kept so stores written before the rename still load.
 */
"inline"
export type PaginatedHistory = { entries: HistoryEntry[]; has_more: boolean }
export type PermissionAccess = "allowed" | "denied" | "unknown"
export type RecordingRetentionPeriod = "never" | "preserve_limit" | "days_3" | "weeks_2" | "months_3"
export type ShortcutBinding = { id: string; name: string; description: string; default_binding: string; current_binding: string }
export type SoundTheme = "marimba" | "pop" | "chime" | "bubble" | "breeze" | "custom"
/**
 * Per-stage engine choice: deterministic rules or the local cleanup model.
 */
export type StageEngine = "deterministic" | "model"
/**
 * Phase of the streaming overlay card, emitted to drive its UI state.
 */
export type StreamPhase = 
/**
 * Receiving audio / live text (or waiting for the stream to begin). Rust
 * does not emit this today; the frontend starts in this phase and Rust only
 * emits transitions away from it.
 */
"listening" | 
/**
 * Finalizing or post-processing, show a spinner.
 */
"working"
/**
 * Emitted to switch the streaming overlay to a working spinner.
 */
export type StreamPhaseEvent = { phase: StreamPhase; 
/**
 * Present only when `phase` is `Working`.
 */
kind?: StreamWorkKind | null }
/**
 * Live transcription snapshot emitted to the overlay during a streaming run.
 * `committed` is the append-only, flicker-free prefix; `tentative` is the
 * volatile suffix the model may still rewrite.
 */
export type StreamTextEvent = { committed: string; tentative: string }
/**
 * Semantic kind of "working" phase, used to localize the spinner label.
 */
export type StreamWorkKind = "transcribing" | "polishing"
/**
 * Theme mode for both webview windows: follow the OS, or force light/dark.
 * The frontend stamps data-theme from this; the backend only stores it.
 */
export type ThemeMode = "system" | "light" | "dark"
/**
 * Which default the machine earns. Serialized to the frontend for onboarding
 * copy ("16 GB detected, full quality").
 */
export type Tier = 
/**
 * >= 14 GB total RAM: Qwen2.5-7B-Instruct Q4_K_M, the exact weights the
 * Ollama default (`qwen2.5:7b`) runs, so migrating costs zero quality.
 */
"full_7b" | 
/**
 * 6-14 GB: Qwen2.5-1.5B-Instruct Q4_K_M, honestly labeled reduced quality.
 */
"compact_1_5b" | 
/**
 * < 6 GB: raw dictation by default; LLM cleanup stays opt-in (0.5B).
 */
"raw"
/**
 * Per-mic Whisper Mode calibration (round 20): measured levels from the
 * optional ~8 s wizard plus the ceilings/floor derived from them. Stored
 * with the microphone it was measured on and IGNORED when a different mic
 * is active (a headset calibration must never govern the built-in mic).
 * When absent (or the device differs) the gate uses the strength defaults.
 */
export type WhisperCalibration = { 
/**
 * The microphone this was measured on ("default" = the system default).
 */
device_name: string; 
/**
 * Measured mean raw frame rms per wizard phase.
 */
ambient_rms: number; normal_rms: number; whisper_rms: number; 
/**
 * Recommended loudness ceilings per strength (envelope semantics).
 */
light_ceiling: number; medium_ceiling: number; high_ceiling: number; 
/**
 * Veto energy floor derived from the room's ambient level.
 */
energy_floor: number; 
/**
 * Whisper/normal separation verdict: "good", "workable", or "poor".
 */
separation: string }
/**
 * Whisper Mode boost strength (whisper_mode itself is the on/off; there is
 * no Off strength).
 */
export type WhisperStrength = "light" | "medium" | "high"
export type WindowsMicrophonePermissionStatus = { supported: boolean; overall_access: PermissionAccess; device_access: PermissionAccess; app_access: PermissionAccess; desktop_app_access: PermissionAccess }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
